### ISSUE TITLE
궁금한게 있는데

### ISSUE THREAD

**Issue by KiRist-code** [Juha3141/JuhaOS#1]
혹시 이거 BufferOverFlow 될건가요
특히 커널영역에서 쉘쪽으로 인자값 받고 계신데 뭔가 될 것 같아서요

**Comment by Juha3141** [comment]
버퍼 오버플로우요? 가능해요, 아마도 코드가 이렇게 메인함수에 있으면:
char test[50];
gets(test)
버퍼오버플로우 취약점이 생기겠죠? 하지만 제 운영체제는 콘솔에서 hex입력이 안되요. 그렇기 때문에 메모리에 직접 접근하는 방법이나 다른 것들이 아니면 "콘솔"에서 버퍼오버플로우를 하는건 힘들겠죠?

**Comment by AkiaCode** [comment]
아마도 아직은 딱히 뭘 할 수 있는 게 없으니까 안되지 더 힘들지 않을까요?

**Comment by Juha3141** [comment]
네 맞아요 ㅋㅋ

**Comment by KiRist-code** [comment]
그렇군요 감사합니다
