### ISSUE TITLE
git clone 했더니 git 푸쉬하신거까지 다 오네요....

### ISSUE THREAD

**Issue by KiRist-code** [Juha3141/JuhaOS#2]
![image](https://user-images.githubusercontent.com/37296174/99792459-74bcf380-2b6a-11eb-8f83-2c3dd1bc9f1a.png)

이런거 .gitnore 쓰시면 될것 같은데 이거 노출되도 되는건가요

**Comment by Juha3141** [comment]
오 이런..

**Comment by AkiaCode** [comment]
@KiRist-code  #3

**Comment by AkiaCode** [comment]
그럼 이제 Close 하셔도 될 거 같아요 @Juha3141

**Comment by aNchor-only** [comment]
> ![image](https://user-images.githubusercontent.com/37296174/99792459-74bcf380-2b6a-11eb-8f83-2c3dd1bc9f1a.png)
> 
> 이런거 .gitnore 쓰시면 될것 같은데 이거 노출되도 되는건가요

IE.. 반동분자다 끌어내

**Comment by KiRist-code** [comment]
@aNchor-only 학교컴인데요

**Comment by aNchor-only** [comment]
학교컴에 vmware?

**Comment by 614project** [comment]
> ![image](https://user-images.githubusercontent.com/37296174/99792459-74bcf380-2b6a-11eb-8f83-2c3dd1bc9f1a.png)
> 
> 이런거 .gitnore 쓰시면 될것 같은데 이거 노출되도 되는건가요

거기 학교컴 참 이상하네요
IE에 웨일브라우저에 모니터 비율이 영...
