### ISSUE TITLE
와 정말 도움되는 방식으로 3년을 보냈구나!

### ISSUE THREAD

**Issue by Pneuma714** [Juha3141/JuhaOS#4]
3년동안 한게 운ㅋ영ㅋ체ㅋ제ㅋ 어디가서 부끄러워서 포트폴리오로 제출이나 할수 있겠니

**Comment by dacoonkr** [comment]
ㅋㅋㄹㅃㅃ
ㅋㅋㄹㅃㅃ
ㅋㅋㄹㅃㅃ

**Comment by muno9748** [comment]
ㅋㅋㄹㅃㅃ
ㅋㅋㄹㅃㅃ
ㅋㅋㄹㅃㅃ

**Comment by Pneuma714** [comment]
ㅋㅋㄹㅃㅃ
ㅋㅋㄹㅃㅃ
ㅋㅋㄹㅃㅃ

**Comment by PERCENTZERO** [comment]
운영체제는 시발 니애미한테나 자랑하고요 ㅋㅋㅋㅋ

**Comment by pmh-only** [comment]
ㄹㅇㅋㅋ

**Comment by pmh-only** [comment]
요즘 시스템 프로그래머가 돈을 벌긴 할 수 있나
웹으로 오세요

**Comment by noeulnight** [comment]
왜 이렇게 삼 ㅋㅋㅋ

**Comment by jwkim101201** [comment]
https://github.com/Pneuma714/TTSchat/issues/1

**Comment by Cresendo82** [comment]
헐;;; 우녕채재라니 그거 참 대단한걸ㄹ요???????
완전 앤트리 개발ㄹ자의 행뽀같내요 ㅋㅋ

**Comment by pmh-only** [comment]
이걸 닫네
